// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds all application configuration
 */
export class Config {
    "general": GeneralConfig;
    "engine": EngineConfig;
    "prompt": PromptConfig;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("general" in $$source)) {
            this["general"] = (new GeneralConfig());
        }
        if (!("engine" in $$source)) {
            this["engine"] = (new EngineConfig());
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = (new PromptConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("general" in $$parsedSource) {
            $$parsedSource["general"] = $$createField0_0($$parsedSource["general"]);
        }
        if ("engine" in $$parsedSource) {
            $$parsedSource["engine"] = $$createField1_0($$parsedSource["engine"]);
        }
        if ("prompt" in $$parsedSource) {
            $$parsedSource["prompt"] = $$createField2_0($$parsedSource["prompt"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * EngineConfig holds translation engine settings
 */
export class EngineConfig {
    "type": EngineType;
    "internal": InternalConfig;
    "terminalAgent": TerminalAgentConfig;
    "ollama": OllamaConfig;

    /** Creates a new EngineConfig instance. */
    constructor($$source: Partial<EngineConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = EngineType.$zero;
        }
        if (!("internal" in $$source)) {
            this["internal"] = (new InternalConfig());
        }
        if (!("terminalAgent" in $$source)) {
            this["terminalAgent"] = (new TerminalAgentConfig());
        }
        if (!("ollama" in $$source)) {
            this["ollama"] = (new OllamaConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): EngineConfig {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("internal" in $$parsedSource) {
            $$parsedSource["internal"] = $$createField1_0($$parsedSource["internal"]);
        }
        if ("terminalAgent" in $$parsedSource) {
            $$parsedSource["terminalAgent"] = $$createField2_0($$parsedSource["terminalAgent"]);
        }
        if ("ollama" in $$parsedSource) {
            $$parsedSource["ollama"] = $$createField3_0($$parsedSource["ollama"]);
        }
        return new EngineConfig($$parsedSource as Partial<EngineConfig>);
    }
}

/**
 * EngineType represents the type of translation engine
 */
export enum EngineType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EngineInternal = "internal",
    EngineTerminalAgent = "terminal-agent",
    EngineOllama = "ollama",
};

/**
 * GeneralConfig holds general application settings
 */
export class GeneralConfig {
    "theme": Theme;
    "language": string;

    /** Creates a new GeneralConfig instance. */
    constructor($$source: Partial<GeneralConfig> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = Theme.$zero;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneralConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneralConfig($$parsedSource as Partial<GeneralConfig>);
    }
}

/**
 * InternalConfig holds internal (Yzma) engine settings
 */
export class InternalConfig {
    "modelPath": string;
    "contextSize": number;

    /** Creates a new InternalConfig instance. */
    constructor($$source: Partial<InternalConfig> = {}) {
        if (!("modelPath" in $$source)) {
            this["modelPath"] = "";
        }
        if (!("contextSize" in $$source)) {
            this["contextSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InternalConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): InternalConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InternalConfig($$parsedSource as Partial<InternalConfig>);
    }
}

/**
 * OllamaConfig holds Ollama engine settings
 */
export class OllamaConfig {
    "host": string;
    "model": string;

    /**
     * seconds
     */
    "timeout": number;

    /** Creates a new OllamaConfig instance. */
    constructor($$source: Partial<OllamaConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OllamaConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): OllamaConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OllamaConfig($$parsedSource as Partial<OllamaConfig>);
    }
}

/**
 * PromptConfig holds prompt settings
 */
export class PromptConfig {
    "template": string;
    "systemPrompt": string;

    /** Creates a new PromptConfig instance. */
    constructor($$source: Partial<PromptConfig> = {}) {
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptConfig($$parsedSource as Partial<PromptConfig>);
    }
}

/**
 * TerminalAgentConfig holds terminal agent settings
 */
export class TerminalAgentConfig {
    "selected": TerminalAgentType;
    "claudeCode": TerminalAgentOption;
    "geminiCli": TerminalAgentOption;
    "codex": TerminalAgentOption;

    /** Creates a new TerminalAgentConfig instance. */
    constructor($$source: Partial<TerminalAgentConfig> = {}) {
        if (!("selected" in $$source)) {
            this["selected"] = TerminalAgentType.$zero;
        }
        if (!("claudeCode" in $$source)) {
            this["claudeCode"] = (new TerminalAgentOption());
        }
        if (!("geminiCli" in $$source)) {
            this["geminiCli"] = (new TerminalAgentOption());
        }
        if (!("codex" in $$source)) {
            this["codex"] = (new TerminalAgentOption());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalAgentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalAgentConfig {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("claudeCode" in $$parsedSource) {
            $$parsedSource["claudeCode"] = $$createField1_0($$parsedSource["claudeCode"]);
        }
        if ("geminiCli" in $$parsedSource) {
            $$parsedSource["geminiCli"] = $$createField2_0($$parsedSource["geminiCli"]);
        }
        if ("codex" in $$parsedSource) {
            $$parsedSource["codex"] = $$createField3_0($$parsedSource["codex"]);
        }
        return new TerminalAgentConfig($$parsedSource as Partial<TerminalAgentConfig>);
    }
}

/**
 * TerminalAgentOption holds settings for a terminal agent
 */
export class TerminalAgentOption {
    /**
     * path to executable (empty = use PATH)
     */
    "executable": string;

    /**
     * additional arguments
     */
    "args": string[];

    /**
     * seconds
     */
    "timeout": number;

    /** Creates a new TerminalAgentOption instance. */
    constructor($$source: Partial<TerminalAgentOption> = {}) {
        if (!("executable" in $$source)) {
            this["executable"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalAgentOption instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalAgentOption {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        return new TerminalAgentOption($$parsedSource as Partial<TerminalAgentOption>);
    }
}

/**
 * TerminalAgentType represents the terminal agent type
 */
export enum TerminalAgentType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AgentClaudeCode = "claude-code",
    AgentGeminiCLI = "gemini-cli",
    AgentCodex = "codex",
};

/**
 * Theme represents the application theme
 */
export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeLight = "light",
    ThemeDark = "dark",
    ThemeSystem = "system",
};

// Private type creation functions
const $$createType0 = GeneralConfig.createFrom;
const $$createType1 = EngineConfig.createFrom;
const $$createType2 = PromptConfig.createFrom;
const $$createType3 = InternalConfig.createFrom;
const $$createType4 = TerminalAgentConfig.createFrom;
const $$createType5 = OllamaConfig.createFrom;
const $$createType6 = TerminalAgentOption.createFrom;
const $$createType7 = $Create.Array($Create.Any);
