// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as SettingService from "./settingservice.js";
import * as TranslateService from "./translateservice.js";
export {
    SettingService,
    TranslateService
};
