// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function GetCurrentConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(3811879968).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateEngineConfig(engine: config$0.EngineConfig): $CancellablePromise<void> {
    return $Call.ByID(999849770, engine);
}

export function UpdateGeneralConfig(general: config$0.GeneralConfig): $CancellablePromise<void> {
    return $Call.ByID(2630718736, general);
}

export function UpdatePromptConfig(prompt: config$0.PromptConfig): $CancellablePromise<void> {
    return $Call.ByID(1991181538, prompt);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
